### ISSUE TITLE
Invalid link error in Get Started guide

### ISSUE THREAD

**Issue by Theosaurus-Rex** [ash-project/ash_hq#13]
Currently, when running locally, navigating to the Get Started guide via either the CTA button on the home page or the book icon in the top nav throws the following error:
```[error] Invalid link %UndefinedFunctionError{arity: 0, function: :version, message: nil, module: nil, reason: nil}
    nil.version()
    (ash_hq 0.1.0) lib/ash_hq_web/pages/docs.ex:453: AshHqWeb.Pages.Docs.render_mix_dep/3
    (ash_hq 0.1.0) lib/ash_hq_web/pages/docs.ex:421: anonymous fn/2 in AshHqWeb.Pages.Docs.render_mix_deps/2
    (elixir 1.13.4) lib/regex.ex:739: Regex.apply_list/5
    (elixir 1.13.4) lib/regex.ex:734: Regex.apply_list/5
    (elixir 1.13.4) lib/regex.ex:669: Regex.replace/4
    (ash_hq 0.1.0) lib/ash_hq_web/pages/docs.ex:122: anonymous fn/2 in AshHqWeb.Pages.Docs."render (overridable 1)"/1
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:494: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:494: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:138: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:803: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:439: Phoenix.LiveView.Channel.mount_handle_params_result/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:1003: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
```

Had a crack at trying to fix this but can't fully grok how the links are being created. The site still runs fine, so not sure what's going on here

**Comment by zachdaniel** [comment]
My suspicion here is that you just haven't imported all the libraries yet. Try running the importer and see if that resolves the issue. Will close for now, but reopen if that doesn't work :)
